version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - automated
    versioning-strategy: increase
    ignore:
      - dependency-name: '@types/node'
        versions: ['>=23.0.0']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - github-actions
      - automated

  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: monthly
