export enum AuditAction {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  HARD_DELETE = 'hard_delete',
  PUBLISH = 'publish',
  UNPUBLISH = 'unpublish',
  BULK_DELETE = 'bulk_delete',
  BULK_UPDATE = 'bulk_update',
  MARK_READ = 'mark_read',
  MARK_ALL_READ = 'mark_all_read',
  UPSERT = 'upsert',
  UPLOAD = 'upload',
  REVOKE = 'revoke',
  RESTORE = 'restore',
  TOGGLE_FEATURED = 'toggle_featured',
  TOGGLE_VISIBILITY = 'toggle_visibility',
  ADD_NOTE = 'add_note',
  UPDATE_ROLE = 'update_role',
  UNLOCK = 'unlock',
  ANONYMIZE = 'anonymize',
  REORDER = 'reorder',
}

export enum AuditResource {
  ACHIEVEMENT = 'achievement',
  BLOG = 'blog',
  AVAILABILITY_STATUS = 'availability_status',
  CHAT_CONVERSATION = 'chat_conversation',
  EXPERIENCE = 'experience',
  FAQ = 'faq',
  API_KEY = 'api_key',
  CASE_STUDY = 'case_study',
  PRESS_FEATURE = 'press_feature',
  NOTIFICATION = 'notification',
  LEAD = 'lead',
  MEDIA = 'media',
  FEATURE_FLAG = 'feature_flag',
  GUEST_APPEARANCE = 'guest_appearance',
  USER = 'user',
  SKILL = 'skill',
  SECTION = 'section',
  SYSTEM_SETTING = 'system_setting',
  SERVICE = 'service',
  TESTIMONIAL = 'testimonial',
  READING_LIST_ITEM = 'reading_list_item',
  PROJECT = 'project',
}
